export enum actionTypes {
  GET_POSTS = '@@GET_POSTS',
  GET_POSTS_SUCCESSFUL = '@@GET_POSTS_SUCCESSFUL',
  GET_POSTS_FAILED = '@@GET_POSTS_FAILED',

  EDIT_POST = '@@EDIT_POST',
  EDIT_POST_SUCCESSFUL ='@@EDIT_POST_SUCCESSFUL',
  EDIT_POST_FAILED = '@@EDIT_POSTS_FAILED',

  ADD_POST = '@@ADD_POST',
  ADD_POST_SUCCESSFUL ='@@ADD_POST_SUCCESSFUL',
  ADD_POST_FAILED = '@@ADD_POSTS_FAILED',

  DELETE_POST_SUCCESSFUL ='@@DELETE_POST_SUCCESSFUL',
  DELETE_POST_FAILED = '@@DELETE_POSTS_FAILED',


}